name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    name: Check types
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Run TypeScript Type Check
        run: npm run type-check

  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Build portal
        run: npm run build-only

  sonar:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            
        - name: Run SonarCloud scanner
          uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/sonarcloud@main
          with:
            sonar-token: ${{ secrets.SONAR_TOKEN }}
