name: Create release package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Build frontend
        run: npm run build-only

      - name: Add version file
        run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > dist/version.json'

      - name: Create tar
        run: tar -C dist -czf nl-irealisatie-zmodules-qualification-register-web_${{ env.RELEASE_VERSION }}.tar.gz ./assets ./index.html ./version.json

      - name: Upload release tar
        uses: actions/upload-artifact@v4
        with:
          name: nl-irealisatie-zmodules-qualification-register-web_${{ env.RELEASE_VERSION }}
          path: nl-irealisatie-zmodules-qualification-register-web_${{ env.RELEASE_VERSION }}.tar.gz
